// ------------------------------------------------
// AUTO-GENERATED SIDEBARS
// ------------------------------------------------

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

module.exports = sidebars;


// ------------------------------------------------
// MANUALLY CONSTRUCTEDSIDEBARS
// ------------------------------------------------
// /** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
// const sidebars = {
//   tutorialSidebar: [
//     {
//       type: 'category',
//       label: 'Getting Started',
//       items: [{ type: 'autogenerated', dirName: 'getting-started' }],
//     },
//     {
//       type: 'category', 
//       label: 'Concepts',
//       items: [{ type: 'autogenerated', dirName: 'Concepts' }],
//     },
//     {
//       type: 'category',
//       label: 'Tutorials',
//       items: [{ type: 'autogenerated', dirName: 'tutorials' }],
//     },
//     {
//       type: 'category',
//       label: 'Developer Tools',
//       items: [{ type: 'autogenerated', dirName: 'developer-tools' }],
//     },
//     {
//       type: 'category',
//       label: 'Intuition Network',
//       items: [{ type: 'autogenerated', dirName: 'network' }],
//     },
//     {
//       type: 'category',
//       label: 'Integrations',
//       items: [{ type: 'autogenerated', dirName: 'integrations' }],
//     },
//     {
//       type: 'category',
//       label: 'Use Cases',
//       items: [{ type: 'autogenerated', dirName: 'use-cases' }],
//     },
//     {
//       type: 'category',
//       label: 'Resources',
//       items: [{ type: 'autogenerated', dirName: 'resources' }],
//     },
//     {
//       type: 'category',
//       label: 'Contribute',
//       items: [{ type: 'doc', id: 'contribute' }],
//     },
//     // ... add more categories in your preferred order
//   ],
// };

// module.exports = sidebars;